services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env # TO-DO: Decide if this is a good idea, because .env contains the environment variables of all containers, not just nginx
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306" # TO-DO: Is this necessary?
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env # TO-DO: Decide the same as above
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    # ports:
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env # TO-DO: Decide the same as above
    restart: always
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/apresas/data/mysql
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/apresas/data/wordpress
      o: bind
